### PR TITLE
Completed Next web clone page

### PR DESCRIPTION
**Pull request by EricMbouwe**
Live Preview Link: https://rawcdn.githack.com/EricMbouwe/The-next-web/13f2898c4452ee7a05f4e177af3d27e67a7d399d/index.html

## EDIT after the first review:
- Added images to icons in the footer section
- Updated Image Sizes
- Updated Responsiveness of Grid Layout

In this project, we created a grayscale heatmap of the smashingmagazine.com

Steps:
Created Header / Navbar and make it fixed for mobile layout
Added backgrounds images and linear gradients backgrounds
Created Grid Sections
Added  Font Weights / Different Font Size
Created a responsive layout for mobile and tablets
Use flex into grids to improve the layout on mobile.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :100:

**Comment by nikasulo** [comment]
# Your work project is really great @DennisOsido and @DennisOsido 
Please consider my comments below, make the appropriate changes and request another review! 

There are a few issues with the responsiveness of your project, I have gone ahead to bring a few of them to your notice below. Please consider them, and take extra looks at the the rest of your project on all screen sizes!

#### Footer Icons
Please consider replacing your footer icons with actual icons.

#### Latest Funding section
Please consider making changes to the width of this section on the mobile screen size (1 grid column). It is currently more narrow than it should be.

#### Image Responsiveness
 Please consider looking into the responsiveness of your images, I think a few improvements can be made. 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by DennisOsido** [comment]
## After the first review:

- Added images to icons in the footer section
- Updated Image Sizes
- Updated Responsiveness of Grid Layout

**Review by rOluochKe — APPROVED** [review]
Hello @EricMbouwe and @DennisOsido 
### Well done :clap: for a good job and for also implementing changes from the previous review. Your project looks good and I, therefore approve of it :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
